# Generated by Django 5.1 on 2024-08-27 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_assessment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('register_number', models.BigIntegerField()),
                ('school_serie', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_semester', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('second_semester', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('third_semester', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('four_semester', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('first_note', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('second_note', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('third_note', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('four_note', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
