# Generated by Django 5.1 on 2024-08-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_studentnotes_delete_assessment_delete_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentNotes',
            new_name='StudentNote',
        ),
    ]
